### ISSUE TITLE
How do you envision defining and enforcing permissions for applications with multiple levels of permissions?

### ISSUE THREAD

**Issue by amoerie** [PolicyServer/PolicyServer.Local#1]
For example, think about hospitals. (I actually make software for hospitals for a living)
They are split up into different departments, with strong boundaries between them.  As a doctor in the cardiology department you are allowed to do all kinds of things within that department, but if you need an anaesthesiologist to come in before an appointment, you are simply not allowed to schedule an appointment for someone in another department, let alone even see those appointments.

In the samples you give in the readme, you even speak about surgeons, doctors and nurses as possible roles for people, but if permissions are linked to roles I fail to see how this can be used in hospitals in real world scenarios.

Taking this even further, a doctor is allowed to do 100% of possible actions within his own schedule, maybe 20% of possible actions within the schedule of a doctor of the same department (they are close colleagues, you can imagine they sometimes step in for one another) and maybe 5% of possible actions within the schedule of a doctor of a different department.

This means that permissions change at three levels already
- Doctor managing schedules of another department
- Doctor managing schedules of same department
- Doctor managing his own schedule

So this is my question: how would you link roles to data defined within an application? And how would you enforce permissions in that scenario?

**Comment by leastprivilege** [comment]
Couple of thoughts here

* the "local" version is only suitable for a single application. To model more complex application/roles/permission relationships, you would need the full version - see https://solliance.net/products/policyserver
* We deliberately didn't try to model "business logic" - we don't think an external system is suited for that. PolicyServer ends at the roles -> permissions boundary. Everything else is modelled far more effectively in your own application (e.g. using a custom ASP.NET Core policy).

**Comment by amoerie** [comment]
I've thought about this some more in the meantime and I think my questions are answered. Thanks!
