### ISSUE TITLE
application roles and permissions for a client using client credentials (no openid/sub/profile stuff).

### ISSUE THREAD

**Issue by VictorioBerra** [PolicyServer/PolicyServer.Local#16]
I am writing an API that will need to support hybrid flow (with a user - MVC app) and client credentials flow (no user - Console App). Right now, the user requirement is just for auditing but may eventually be more important so I want to learn some strategies early on.

I know that traditionally, for permissions we can create multiple scopes for our protected resource as seen in the [IS4 sample clients](https://github.com/IdentityServer/IdentityServer4/blob/dev/host/Configuration/Resources.cs#L39-L76) `"api2.full_access", "api2.read_only", "api2.internal"`, and then we use the `ScopePolicy` stuff to lock down our API as [explained in the docs](https://identityserver4.readthedocs.io/en/release/topics/apis.html#validating-scopes).

I wrote some sample apps and I found out that I could add static claims such as a `role` with a value onto my calling client and that would successfully get mapped to app roles and perms via `AddAuthorizationPermissionPolicies()`. But my main question is, is this the right way? Or should I be getting a little more custom by say mapping the scope off to a role first or something? I don't want to write too much custom code, I prefer to stay in the realm of the framework I am using which in this case will be IS4 with Admin API and Enterprise PolicyServer.

**Comment by michelebusta** [comment]
Hi Victor, did you post this to the IS4 issue tracker? Sounds more like an IS4 question here, not really a policyserver.io question?

**Comment by VictorioBerra** [comment]
I think this is a PS question. I am asking how scopes would be mapped to roles/perms.

**Comment by brockallen** [comment]
Scopes are client permissions granted by the user via consent or via admin via config. They're unrelated to user permissions.

**Comment by VictorioBerra** [comment]
Okay, ill think about my security architecture a bit more. When I get something I am comfortable with, perhaps I will detail it here and get a second opinion. Right now, I have a UI and an API and the API will need to allow humans and machines.
