### ISSUE TITLE
Will this work with client credentials out of the box?

### ISSUE THREAD

**Issue by VictorioBerra** [PolicyServer/PolicyServer.Local#24]
Client creds mean you get a token with no subject.

Is that supported? Why can't we look at the client_id claim and treat that as a subject?

Would a PR be accepted?

**Comment by leastprivilege** [comment]
You can pass in whatever claims you like to the Evaluate method. But client id and sub have different semantics.

We are not planning to make any changes to this repo - this is sample. If you wish to change it, feel free to do that in your own fork.

**Comment by VictorioBerra** [comment]
Before I go and make my own changes, what semantics between sub and client_id do you mean?

**Comment by leastprivilege** [comment]
They mean different things. That's all.
