### ISSUE TITLE
Is it possible to make PolicyResult extendable?

### ISSUE THREAD

**Issue by noufionline** [PolicyServer/PolicyServer.Local#6]
Hi @leastprivilege 

If you can make set accessors of Permissions and Roles properties of PolicyResult class as public,  then it would be easy for creating a custom implementation of IPolicyServerClient.

**Comment by brockallen** [comment]
Is this for doing unit testing?

**Comment by noufionline** [comment]
Hi @brockallen. I was just trying to plug-gin some custom implementations to work with PolicyServer local by creating a custom implementation of IPolicyServerClient. The idea is to get all my claims from our custom database and bake inside PolicyServerClient implementation so that no need to depend on json file. But that is only possible if the PolicyResult has public setter for Permissions and Roles properties. 
I hope I was able to explain it better.

**Comment by leastprivilege** [comment]
> The idea is to get all my claims from our custom database and bake inside PolicyServerClient implementation so that no need to depend on json 

I still don't follow - there are two independent things here

* claims are input to the policy. You can create the claims in any way you want - IOW - if you want to load the input claims from a database, why not wrap the policy server client in a custom service that does the input claim loading.

* policies define the mapping from input claims to roles and permissions. In the Local version this is using the configuration system (which btw is extensible - so you could load the polices from somewhere else than a json file).

If you need more advanced scenarios I would recommend using the commercial version (or fork Local and go from there)

**Comment by Jenan** [comment]
@leastprivilege - I think @noufionline had valid requirement. This local version works really well. I have prepared local version with EF, but only one limit are internal setters on `PolicyResult`.  I've created fork from Local version and rework `PolicyResult` but it would be nice - install `PolicyServer.Local` as nuget package and extend with for example with EF implementation of local store. :) Please consider it.

**Comment by leastprivilege** [comment]
OK - PR please.

**Comment by noufionline** [comment]
Thanks!
